name: 'get_mem'

services:
  db:
    container_name: db
    image: postgres:latest
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database", "--quiet"]
      interval: 3s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env

  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  minio_api:
    container_name: minio_api
    build: 
      context: .
      dockerfile: minio_api.Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      minio:
        condition: service_healthy

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
volumes:
  postgres_data:
  minio-storage: